# Generated by Django 4.1.7 on 2023-02-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pub_date',
            new_name='p_date',
        ),
    ]
