# Generated by Django 4.1.7 on 2023-02-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsks', '0002_rename_category_name_category_c_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
